services:
  mysql:
    image: mysql:8.0.34
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=homework
      - MYSQL_USER=homework
      - MYSQL_PASSWORD=pass
    volumes:
      - ./schema:/docker-entrypoint-initdb.d